<?php
 goto FBdzl; FBdzl: session_start(); goto Ycxi4; cyz4r: $products_data = json_decode($products_json, true); goto w6nog; SHQEe: foreach ($products_data as $category => $products) { foreach ($products as $product) { $product["\143\x61\164\x65\147\x6f\x72\x79"] = $category; $all_products[] = $product; } } goto x20x3; qRApw: if (isset($_GET["\x73\x75\143\x63\145\163\x73"])) { ?>
<div class="alert alert-success">İşlem başarıyla tamamlandı.</div><?php  } goto Hp0_s; Ycxi4: if (!isset($_SESSION["\x61\144\155\x69\x6e\x5f\154\x6f\147\147\x65\x64\x5f\151\156"])) { header("\114\157\x63\141\164\151\157\156\x3a\40\x6c\x6f\x67\151\156\56\x70\x68\160"); die; } goto PMxNs; w6nog: $all_products = array(); goto SHQEe; SSgpc: foreach ($all_products as $product) { ?>
<tr><td><?php  echo htmlspecialchars($product["\151\x64"]); ?>
</td><td><img alt="<?php  echo htmlspecialchars($product["\156\141\x6d\145"]); ?>
"src="<?php  echo htmlspecialchars($product["\x69\155\141\147\x65"]); ?>
"style="width:50px;height:50px;object-fit:cover"></td><td><?php  echo htmlspecialchars($product["\x6e\x61\155\x65"]); ?>
</td><td><?php  echo ucfirst(htmlspecialchars($product["\x63\x61\164\145\x67\x6f\162\171"])); ?>
</td><td><a class="btn btn-sm btn-primary me-1"href="product-edit.php?id=<?php  echo $product["\x69\144"]; ?>
"><i class="bi bi-pencil"></i> </a><a class="btn btn-sm btn-danger"href="products.php?action=delete&id=<?php  echo $product["\x69\x64"]; ?>
"onclick='return confirm("Bu ürünü silmek istediğinizden emin misiniz?")'><i class="bi bi-trash"></i></a></td></tr><?php  } goto dFZtK; Hp0_s: ?>
<div class="table-responsive"><table class="table table-hover table-striped"><thead><tr><th>ID</th><th>Resim</th><th>Ürün Adı</th><th>Kategori</th><th>İşlemler</th></tr></thead><tbody><?php  goto SSgpc; IAD8j: ?>
<!doctypehtml><html lang="tr"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1"name="viewport"><title>Ürün Yönetimi - Admin Panel</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"rel="stylesheet"></head><body><nav class="bg-dark navbar navbar-dark"><div class="container-fluid"><a class="navbar-brand"href="index.php">Elegance Textile</a><div class="d-flex"><a class="btn btn-sm btn-outline-light"href="logout.php">Çıkış Yap</a></div></div></nav><div class="container-fluid"><div class="row"><div class="bg-dark col-lg-2 col-md-3 collapse d-md-block sidebar"><div class="pt-3 position-sticky"><ul class="flex-column nav"><li class="nav-item"><a class="nav-link text-white"href="index.php"><i class="bi bi-house"></i> Ana Sayfa</a></li><li class="nav-item"><a class="nav-link text-white active"href="products.php"><i class="bi bi-box"></i> Ürünler</a></li><li class="nav-item"><a class="nav-link text-white"href="categories.php"><i class="bi bi-tags"></i> Kategoriler</a></li><li class="nav-item"><a class="nav-link text-white"href="logout.php"><i class="bi bi-box-arrow-right"></i> Çıkış</a></li></ul></div></div><main class="col-lg-10 col-md-9 ms-sm-auto px-md-4"><div class="d-flex align-items-center border-bottom flex-md-nowrap flex-wrap justify-content-between mb-3 pb-2 pt-3"><h1 class="h2">Ürün Yönetimi</h1><a class="btn btn-primary"href="product-add.php"><i class="bi bi-plus"></i> Yeni Ürün Ekle</a></div><?php  goto qRApw; PMxNs: $products_json = file_get_contents(__DIR__ . "\x2f\56\x2e\x2f\160\162\x6f\x64\165\143\164\163\x2e\x6a\163\157\156"); goto cyz4r; x20x3: if (isset($_GET["\141\143\164\x69\x6f\156"]) && $_GET["\141\x63\164\x69\x6f\x6e"] === "\144\145\154\145\x74\145" && isset($_GET["\x69\144"])) { $id_to_delete = (int) $_GET["\151\x64"]; foreach ($products_data as $category => &$products) { foreach ($products as $key => $product) { if ($product["\151\x64"] === $id_to_delete) { unset($products[$key]); $products = array_values($products); file_put_contents(__DIR__ . "\x2f\x2e\x2e\x2f\160\162\157\144\x75\x63\x74\163\56\x6a\163\x6f\156", json_encode($products_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)); header("\114\x6f\143\x61\x74\151\x6f\x6e\x3a\x20\160\x72\157\144\165\143\x74\163\x2e\160\x68\160\77\163\x75\x63\x63\145\163\163\75\61"); die; } } } } goto IAD8j; dFZtK: ?>
</tbody></table></div></main></div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></body></html>