<?php
 goto hIOWa; joqQZ: if (file_exists($advanceRequestsFile)) { $advanceRequests = json_decode(file_get_contents($advanceRequestsFile), true); for ($i = 1; $i <= 12; $i++) { $month = date("\106", mktime(0, 0, 0, $i, 1)); $advanceStatsByMonth[$month] = 0; } foreach ($departments as $dept) { $advanceStatsByDepartment[$dept] = 0; } foreach ($advanceRequests as $request) { if ($request["\163\164\x61\164\x75\x73"] === "\x61\160\160\x72\157\166\x65\x64") { $month = date("\106", strtotime($request["\143\162\x65\x61\x74\x65\144\137\x61\x74"])); $advanceStatsByMonth[$month] += $request["\x61\155\x6f\x75\x6e\164"]; $advanceStatsByDepartment[$request["\144\x65\x70\x61\x72\x74\x6d\145\156\164"]] += $request["\141\x6d\157\x75\x6e\x74"]; } } } goto U8iaP; kAKA4: $employeesFile = "\x64\x61\164\141\57\x65\x6d\x70\154\157\x79\145\145\x73\x2e\x6a\163\x6f\x6e"; goto wvzYF; XI0_N: ?>
</ul></nav><div class="sidebar-footer"><a href="profile.php"><i class="fas fa-user-circle"></i> Profil</a> <a href="logout.php"><i class="fas fa-sign-out-alt"></i> Çıkış</a></div></aside><main class="main-content"><header class="header"><div class="header-left"><button class="sidebar-toggle"id="sidebar-toggle"><i class="fas fa-bars"></i></button><h2>Raporlar</h2></div><div class="header-right"><div class="notification"><i class="fas fa-bell"></i> <span class="badge">3</span></div><div class="date-time"><span id="current-date"></span> <span id="current-time"></span></div></div></header><div class="content-wrapper"><div class="container-fluid"><div class="mb-4 row"><div class="col-md-3"><div class="card text-white bg-primary"><div class="card-body"><h5 class="card-title">Toplam Personel</h5><h2 class="card-text"><?php  goto Xm544; cU2ZC: echo json_encode(array_keys($lateEntryStatsByMonth)); goto Z1GOA; wCKIb: $approvedAdvances = 0; goto lFvpC; xQcYW: echo json_encode(array_keys($advanceStatsByDepartment)); goto Ns3DK; BtbDH: $advanceStatsByMonth = array(); goto sdCBS; MJj4I: $leaveStatsByMonth = array(); goto TldtZ; P9mWh: echo json_encode(array_values($leaveStatsByMonth)); goto AzEUF; QOldG: if (file_exists($employeesFile)) { $employees = json_decode(file_get_contents($employeesFile), true); foreach ($employees as $employee) { if (!in_array($employee["\144\x65\160\x61\162\x74\x6d\x65\x6e\164"], $departments)) { $departments[] = $employee["\144\145\160\x61\x72\164\x6d\145\156\164"]; $departmentEmployeeCounts[$employee["\x64\145\160\x61\162\x74\155\x65\x6e\164"]] = 0; } $departmentEmployeeCounts[$employee["\x64\145\x70\141\x72\164\155\x65\156\164"]]++; } sort($departments); } goto qTiOO; YpakN: ?>
</div><div id="attendance-data-labels"style="display:none"><?php  goto dKkvW; vEcaR: echo json_encode(array_keys($lateEntryStatsByMonth)); goto E5Zcn; fgmdD: ?>
</div><div id="leave-data-labels"style="display:none"><?php  goto UQd3I; E5Zcn: ?>
</div><div id="late-entry-data-values"style="display:none"><?php  goto SmaWV; MNZMO: echo count($departments); goto QTq3d; U2L5m: if ($userRole == "\x6d\x61\156\x61\147\145\x72") { ?>
<li><a href="team_management.php"><i class="fas fa-users"></i> Ekip Yönetimi</a></li><li><a href="approval_requests.php"><i class="fas fa-tasks"></i> Onay Bekleyen Talepler</a></li><?php  } goto qpi5U; QTq3d: ?>
</h2><i class="fas card-icon fa-2x fa-building"></i></div></div></div><div class="col-md-3"><div class="card text-white bg-warning"><div class="card-body"><h5 class="card-title">Onaylanan İzinler</h5><h2 class="card-text"><?php  goto EQpzX; wD5QW: echo json_encode(array_keys($advanceStatsByMonth)); goto TyLSP; W3V0L: $advanceRequests = array(); goto BtbDH; P3Jkl: $userId = $_SESSION["\165\163\145\162\137\151\x64"]; goto l017h; iZnlG: echo $userName; goto ty9w2; XPZho: if (file_exists($attendanceFile)) { $attendance = json_decode(file_get_contents($attendanceFile), true); for ($i = 1; $i <= 12; $i++) { $month = date("\x46", mktime(0, 0, 0, $i, 1)); $attendanceStatsByMonth[$month] = 0; $lateEntryStatsByMonth[$month] = 0; } foreach ($departments as $dept) { $attendanceStatsByDepartment[$dept] = array("\x74\157\164\x61\x6c" => 0, "\x6c\141\x74\x65" => 0); } foreach ($attendance as $record) { if ($record["\164\x79\160\x65"] === "\145\x6e\164\162\x79") { $employeeDept = ''; foreach ($employees as $employee) { if ($employee["\151\144"] == $record["\x65\155\x70\154\x6f\171\145\x65\137\151\x64"]) { $employeeDept = $employee["\144\145\x70\141\x72\164\155\145\156\x74"]; break; } } $month = date("\x46", strtotime($record["\144\141\x74\x65"])); $attendanceStatsByMonth[$month]++; $entryTime = strtotime($record["\164\151\155\x65"]); $startTime = strtotime("\x30\71\x3a\x30\x30\x3a\60\60"); if ($entryTime > $startTime) { $lateEntryStatsByMonth[$month]++; if (!empty($employeeDept)) { $attendanceStatsByDepartment[$employeeDept]["\154\x61\x74\145"]++; } } if (!empty($employeeDept)) { $attendanceStatsByDepartment[$employeeDept]["\x74\x6f\164\x61\154"]++; } } } } goto TPEN6; JvoPU: foreach ($leaveRequests as $request) { if ($request["\163\164\x61\164\165\x73"] === "\141\160\x70\x72\157\166\x65\144") { $approvedLeaves++; } } goto J7rdc; SmaWV: echo json_encode(array_values($lateEntryStatsByMonth)); goto nXyeK; Nmk2k: echo json_encode(array_values($advanceStatsByDepartment)); goto q6kAS; ZUPJa: $attendanceStatsByDepartment = array(); goto OLrhp; rEc7d: echo json_encode(array_keys($departmentEmployeeCounts)); goto kT4Yl; nK68B: ?>
</h2><i class="fas card-icon fa-2x fa-money-bill-wave"></i></div></div></div></div><div class="mb-4 row"><div class="col-md-6"><div class="card"><div class="card-header"><h5 class="mb-0">Departman Dağılımı</h5></div><div class="card-body"><canvas id="departmentChart"></canvas></div></div></div><div class="col-md-6"><div class="card"><div class="card-header"><h5 class="mb-0">Aylık İzin Kullanımı</h5></div><div class="card-body"><canvas id="leaveChart"></canvas></div></div></div></div><div class="mb-4 row"><div class="col-md-6"><div class="card"><div class="card-header"><h5 class="mb-0">Aylık Giriş İstatistikleri</h5></div><div class="card-body"><canvas id="attendanceChart"></canvas></div></div></div><div class="col-md-6"><div class="card"><div class="card-header"><h5 class="mb-0">Geç Giriş İstatistikleri</h5></div><div class="card-body"><canvas id="lateEntryChart"></canvas></div></div></div></div><div class="mb-4 row"><div class="col-md-6"><div class="card"><div class="card-header"><h5 class="mb-0">Aylık Avans Ödemeleri</h5></div><div class="card-body"><canvas id="advanceChart"></canvas></div></div></div><div class="col-md-6"><div class="card"><div class="card-header"><h5 class="mb-0">Departman Bazlı Avans Dağılımı</h5></div><div class="card-body"><canvas id="departmentAdvanceChart"></canvas></div></div></div></div><div class="mb-4 row"><div class="col-md-12"><div class="card"><div class="card-header"><h5 class="mb-0">Departman Performans Özeti</h5></div><div class="card-body"><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Departman</th><th>Personel Sayısı</th><th>Kullanılan İzin (Gün)</th><th>Toplam Giriş Sayısı</th><th>Geç Giriş Sayısı</th><th>Geç Giriş Oranı</th><th>Toplam Avans (₺)</th></tr></thead><tbody><?php  goto TBdC1; sz8Iy: echo json_encode(array_values($attendanceStatsByMonth)); goto JdWrd; utvbg: echo json_encode(array_values($advanceStatsByMonth)); goto GHEKY; QmiWh: ?>
</div><div id="leave-data-values"style="display:none"><?php  goto DcI4f; lFvpC: foreach ($advanceRequests as $request) { if ($request["\x73\164\141\x74\165\x73"] === "\x61\x70\160\x72\x6f\166\145\x64") { $approvedAdvances++; } } goto wIFYz; BKjgH: ?>
</h2><i class="fas card-icon fa-2x fa-users"></i></div></div></div><div class="col-md-3"><div class="card text-white bg-success"><div class="card-body"><h5 class="card-title">Toplam Departman</h5><h2 class="card-text"><?php  goto MNZMO; RIEVK: ?>
, datasets: [{ label: 'Kullanılan İzin Günleri', data:<?php  goto P9mWh; UQd3I: echo json_encode(array_keys($leaveStatsByMonth)); goto QmiWh; nXyeK: ?>
</div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script src="https://code.jquery.com/jquery-3.6.0.min.js"></script><script src="js/main.js"></script><script src="js/reports.js"></script>// Department Distribution Chart const departmentCtx = document.getElementById('departmentChart').getContext('2d'); const departmentChart = new Chart(departmentCtx, { type: 'pie', data: { labels:<?php  goto Pb5cE; up_B1: if ($userRole == "\141\144\155\x69\x6e") { echo "\xc4\260\x4b\x20\x59\303\xb6\x6e\145\164\x69\143\x69\163\151"; } else { if ($userRole == "\155\141\156\x61\x67\145\x72") { echo "\x42\x69\162\151\x6d\40\x4d\xc3\274\x64\303\xbc\162\303\274"; } else { echo "\120\145\162\163\157\156\145\x6c"; } } goto qP0kf; TPEN6: $advanceRequestsFile = "\144\141\164\141\x2f\x61\x64\166\141\156\143\145\137\x72\145\x71\165\145\x73\164\163\x2e\x6a\163\x6f\156"; goto W3V0L; qpi5U: if ($userRole == "\141\144\155\x69\156") { ?>
<li><a href="employee_management.php"><i class="fas fa-user-cog"></i> Personel Yönetimi</a></li><li><a href="department_management.php"><i class="fas fa-building"></i> Departman Yönetimi</a></li><li><a href="card_management.php"><i class="fas fa-id-card"></i> Kart Yönetimi</a></li><li><a href="reports.php"class="active"><i class="fas fa-chart-bar"></i> Raporlar</a></li><?php  } goto XI0_N; wIFYz: echo $approvedAdvances; goto nK68B; LY8qZ: ?>
, datasets: [{ data:<?php  goto BYaag; J7rdc: echo $approvedLeaves; goto qxPaQ; AzEUF: ?>
, backgroundColor: '#4e73df', borderColor: '#4e73df', borderWidth: 1 }] }, options: { maintainAspectRatio: false, scales: { yAxes: [{ ticks: { beginAtZero: true } }] } } }); // Monthly Attendance Chart const attendanceCtx = document.getElementById('attendanceChart').getContext('2d'); const attendanceChart = new Chart(attendanceCtx, { type: 'line', data: { labels:<?php  goto BsK2V; OLrhp: $lateEntryStatsByMonth = array(); goto XPZho; UyXIY: if ($_SESSION["\162\157\154\x65"] !== "\141\x64\x6d\x69\156") { header("\x4c\x6f\x63\x61\x74\151\x6f\156\72\40\151\x6e\144\145\170\56\x70\x68\160"); die; } goto P3Jkl; COEO3: ?>
</div><div id="attendance-data-values"style="display:none"><?php  goto MoXnY; pqCaR: echo json_encode(array_values($departmentEmployeeCounts)); goto fgmdD; Ns3DK: ?>
, datasets: [{ data:<?php  goto Nmk2k; qTiOO: $leaveRequestsFile = "\144\141\164\141\x2f\x6c\145\x61\x76\145\x5f\x72\x65\x71\165\x65\163\x74\x73\x2e\x6a\163\x6f\x6e"; goto GFnUu; wvzYF: $employees = array(); goto BlFFj; U8iaP: ?>
<!doctypehtml><html lang="tr"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1"name="viewport"><title>HRMS - Raporlar</title><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/animate.css@4.1.1/animate.min.css"rel="stylesheet"><link href="css/style.css"rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script></head><body><div class="app-container"><aside class="sidebar"><div class="sidebar-header"><img alt="HRMS Logo"src="img/logo.png"class="logo"><h3>HRMS</h3></div><div class="user-info"><div class="user-avatar"><img alt="User Avatar"src="img/avatars/default.png"></div><div class="user-details"><h4><?php  goto iZnlG; mvmql: ?>
</div><div id="late-entry-data-labels"style="display:none"><?php  goto vEcaR; qhuyH: echo json_encode(array_keys($leaveStatsByMonth)); goto RIEVK; BYaag: echo json_encode(array_values($departmentEmployeeCounts)); goto t8mlp; t8mlp: ?>
, backgroundColor: [ '#4e73df', '#1cc88a', '#36b9cc', '#f6c23e', '#e74a3b', '#5a5c69', '#858796', '#6610f2', '#6f42c1', '#fd7e14', '#20c9a6', '#27a844' ], hoverBackgroundColor: [ '#2e59d9', '#17a673', '#2c9faf', '#dda20a', '#be2617', '#3a3b45', '#60616f', '#5d0cdb', '#5d37a8', '#dc6a03', '#169b80', '#1e8e39' ], hoverBorderColor: "rgba(234, 236, 244, 1)", }] }, options: { maintainAspectRatio: false, tooltips: { backgroundColor: "rgb(255,255,255)", bodyFontColor: "#858796", borderColor: '#dddfeb', borderWidth: 1, xPadding: 15, yPadding: 15, displayColors: false, caretPadding: 10, }, legend: { display: true, position: 'bottom' }, cutoutPercentage: 0, }, }); // Monthly Leave Usage Chart const leaveCtx = document.getElementById('leaveChart').getContext('2d'); const leaveChart = new Chart(leaveCtx, { type: 'bar', data: { labels:<?php  goto qhuyH; hIOWa: session_start(); goto v6fVA; v6fVA: if (!isset($_SESSION["\165\x73\x65\x72\137\151\x64"])) { header("\114\157\x63\141\164\x69\x6f\156\x3a\x20\x6c\157\147\x69\x6e\x2e\x70\x68\160"); die; } goto UyXIY; qxPaQ: ?>
</h2><i class="fas card-icon fa-2x fa-calendar-check"></i></div></div></div><div class="col-md-3"><div class="card text-white bg-info"><div class="card-body"><h5 class="card-title">Onaylanan Avanslar</h5><h2 class="card-text"><?php  goto wCKIb; XIUV0: echo json_encode(array_values($lateEntryStatsByMonth)); goto HuawI; CCQc9: ?>
, datasets: [{ label: 'Toplam Giriş Sayısı', data:<?php  goto sz8Iy; OWaH8: ?>
</tbody></table></div></div></div></div></div></div></div></main></div><div id="department-data-labels"style="display:none"><?php  goto rEc7d; Xm544: echo count($employees); goto BKjgH; kT4Yl: ?>
</div><div id="department-data-values"style="display:none"><?php  goto pqCaR; GHEKY: ?>
, backgroundColor: '#36b9cc', borderColor: '#36b9cc', borderWidth: 1 }] }, options: { maintainAspectRatio: false, scales: { yAxes: [{ ticks: { beginAtZero: true, callback: function(value) { return value.toLocaleString('tr-TR', { style: 'currency', currency: 'TRY' }); } } }] }, tooltips: { callbacks: { label: function(tooltipItem, data) { return tooltipItem.yLabel.toLocaleString('tr-TR', { style: 'currency', currency: 'TRY' }); } } } } }); // Department Advance Distribution Chart const departmentAdvanceCtx = document.getElementById('departmentAdvanceChart').getContext('2d'); const departmentAdvanceChart = new Chart(departmentAdvanceCtx, { type: 'doughnut', data: { labels:<?php  goto xQcYW; Pb5cE: echo json_encode(array_keys($departmentEmployeeCounts)); goto LY8qZ; ty9w2: ?>
</h4><p><?php  goto up_B1; TldtZ: $leaveStatsByDepartment = array(); goto NJcGC; DBvBG: $userRole = $_SESSION["\x72\x6f\x6c\x65"]; goto kAKA4; HuawI: ?>
, backgroundColor: '#e74a3b', borderColor: '#e74a3b', borderWidth: 1 }] }, options: { maintainAspectRatio: false, scales: { yAxes: [{ ticks: { beginAtZero: true } }] } } }); // Monthly Advance Payment Chart const advanceCtx = document.getElementById('advanceChart').getContext('2d'); const advanceChart = new Chart(advanceCtx, { type: 'bar', data: { labels:<?php  goto wD5QW; BlFFj: $departments = array(); goto X8sSe; BsK2V: echo json_encode(array_keys($attendanceStatsByMonth)); goto CCQc9; G3QWX: $attendance = array(); goto fQAF3; MoXnY: echo json_encode(array_values($attendanceStatsByMonth)); goto mvmql; KSpQW: $attendanceFile = "\x64\x61\x74\x61\57\x61\x74\164\145\156\144\x61\156\x63\x65\x2e\x6a\x73\157\156"; goto G3QWX; fQAF3: $attendanceStatsByMonth = array(); goto ZUPJa; qP0kf: ?>
</p></div></div><nav class="sidebar-nav"><ul><li><a href="index.php"><i class="fas fa-home"></i> Ana Sayfa</a></li><li><a href="attendance.php"><i class="fas fa-clock"></i> Giriş/Çıkış Kayıtları</a></li><li><a href="leave_requests.php"><i class="fas fa-calendar-alt"></i> İzin Talepleri</a></li><li><a href="advance_requests.php"><i class="fas fa-money-bill-wave"></i> Avans Talepleri</a></li><?php  goto U2L5m; GFnUu: $leaveRequests = array(); goto MJj4I; TyLSP: ?>
, datasets: [{ label: 'Avans Ödemeleri (₺)', data:<?php  goto utvbg; sdCBS: $advanceStatsByDepartment = array(); goto joqQZ; X8sSe: $departmentEmployeeCounts = array(); goto QOldG; JdWrd: ?>
, backgroundColor: 'rgba(28, 200, 138, 0.2)', borderColor: '#1cc88a', borderWidth: 2, pointBackgroundColor: '#1cc88a', pointBorderColor: '#1cc88a', pointHoverBackgroundColor: '#1cc88a', pointHoverBorderColor: '#1cc88a', pointRadius: 3, pointHoverRadius: 5, fill: true }] }, options: { maintainAspectRatio: false, scales: { yAxes: [{ ticks: { beginAtZero: true } }] } } }); // Late Entry Chart const lateEntryCtx = document.getElementById('lateEntryChart').getContext('2d'); const lateEntryChart = new Chart(lateEntryCtx, { type: 'bar', data: { labels:<?php  goto cU2ZC; NJcGC: if (file_exists($leaveRequestsFile)) { $leaveRequests = json_decode(file_get_contents($leaveRequestsFile), true); for ($i = 1; $i <= 12; $i++) { $month = date("\106", mktime(0, 0, 0, $i, 1)); $leaveStatsByMonth[$month] = 0; } foreach ($departments as $dept) { $leaveStatsByDepartment[$dept] = 0; } foreach ($leaveRequests as $request) { if ($request["\163\164\x61\x74\165\x73"] === "\x61\160\160\x72\x6f\x76\x65\x64") { $month = date("\x46", strtotime($request["\163\x74\141\x72\164\137\144\141\164\x65"])); $leaveStatsByMonth[$month] += $request["\x64\141\x79\163"]; $leaveStatsByDepartment[$request["\x64\x65\160\141\162\x74\155\x65\156\164"]] += $request["\x64\x61\x79\x73"]; } } } goto KSpQW; l017h: $userName = $_SESSION["\x6e\x61\155\145"]; goto DBvBG; TBdC1: foreach ($departments as $dept) { ?>
<tr><td><?php  echo $dept; ?>
</td><td><?php  echo $departmentEmployeeCounts[$dept]; ?>
</td><td><?php  echo $leaveStatsByDepartment[$dept]; ?>
</td><td><?php  echo $attendanceStatsByDepartment[$dept]["\164\x6f\164\x61\x6c"]; ?>
</td><td><?php  echo $attendanceStatsByDepartment[$dept]["\154\141\x74\x65"]; ?>
</td><td><?php  $lateRatio = 0; if ($attendanceStatsByDepartment[$dept]["\164\157\164\x61\154"] > 0) { $lateRatio = $attendanceStatsByDepartment[$dept]["\x6c\x61\x74\145"] / $attendanceStatsByDepartment[$dept]["\x74\157\164\x61\154"] * 100; } echo number_format($lateRatio, 2) . "\45"; ?>
</td><td><?php  echo number_format($advanceStatsByDepartment[$dept], 2, "\x2c", "\x2e"); ?>
₺</td></tr><?php  } goto OWaH8; EQpzX: $approvedLeaves = 0; goto JvoPU; dKkvW: echo json_encode(array_keys($attendanceStatsByMonth)); goto COEO3; DcI4f: echo json_encode(array_values($leaveStatsByMonth)); goto YpakN; Z1GOA: ?>
, datasets: [{ label: 'Geç Giriş Sayısı', data:<?php  goto XIUV0; q6kAS: ?>
, backgroundColor: [ '#4e73df', '#1cc88a', '#36b9cc', '#f6c23e', '#e74a3b', '#5a5c69', '#858796', '#6610f2', '#6f42c1', '#fd7e14', '#20c9a6', '#27a844' ], hoverBackgroundColor: [ '#2e59d9', '#17a673', '#2c9faf', '#dda20a', '#be2617', '#3a3b45', '#60616f', '#5d0cdb', '#5d37a8', '#dc6a03', '#169b80', '#1e8e39' ], hoverBorderColor: "rgba(234, 236, 244, 1)", }] }, options: { maintainAspectRatio: false, tooltips: { backgroundColor: "rgb(255,255,255)", bodyFontColor: "#858796", borderColor: '#dddfeb', borderWidth: 1, xPadding: 15, yPadding: 15, displayColors: false, caretPadding: 10, callbacks: { label: function(tooltipItem, data) { const value = data.datasets[0].data[tooltipItem.index]; return value.toLocaleString('tr-TR', { style: 'currency', currency: 'TRY' }); } } }, legend: { display: true, position: 'bottom' }, cutoutPercentage: 50, }, });</body></html>