<?php
 goto oYzbo; rvyk9: ?>
<!doctypehtml><html lang="tr"><head><meta charset="UTF-8"><meta content="width=device-width,initial-scale=1"name="viewport"><title>Ürün Yönetimi</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"rel="stylesheet"></head><body><div class="container-fluid"><div class="row"><div class="bg-dark col-lg-2 col-md-3 collapse d-md-block sidebar"><div class="pt-3 position-sticky"><ul class="flex-column nav"><li class="nav-item"><a class="nav-link text-white"href="index.php"><i class="bi bi-house"></i> Ana Sayfa</a></li><li class="nav-item"><a class="nav-link text-white active"href="products.php"><i class="bi bi-box"></i> Ürünler</a></li><li class="nav-item"><a class="nav-link text-white"href="logout.php"><i class="bi bi-box-arrow-right"></i> Çıkış</a></li></ul></div></div><main class="col-lg-10 col-md-9 ms-sm-auto px-md-4"><div class="pt-3 align-items-center border-bottom d-flex flex-md-nowrap flex-wrap justify-content-between mb-3 pb-2"><h1 class="h2">Ürün Yönetimi</h1></div><div class="table-responsive"><table class="table table-striped"><thead><tr><th>ID</th><th>Resim</th><th>Ürün Adı</th><th>Kategori</th><th>Fiyat</th><th>İşlemler</th></tr></thead><tbody><?php  goto OINos; VVtbl: $products_data = json_decode($products_json, true); goto IJLym; L_VT1: foreach ($products_data as $category => $products) { foreach ($products as $product) { $product["\143\x61\164\x65\147\x6f\x72\171"] = $category; $all_products[] = $product; } } goto rvyk9; OINos: foreach ($all_products as $product) { ?>
<tr><td><?php  echo $product["\151\x64"]; ?>
</td><td><img alt="<?php  echo $product["\156\141\155\x65"]; ?>
"src="<?php  echo $product["\x69\155\141\147\145"]; ?>
"style="width:50px;height:50px;object-fit:cover"></td><td><?php  echo $product["\x6e\141\155\145"]; ?>
</td><td><?php  echo ucfirst($product["\x63\x61\164\145\147\157\162\171"]); ?>
</td><td><?php  echo $product["\x70\x72\x69\x63\145"]; ?>
</td><td><a class="btn btn-sm btn-primary me-1"href="#">Düzenle</a> <a class="btn btn-sm btn-danger"href="#">Sil</a></td></tr><?php  } goto AEE5F; oYzbo: session_start(); goto mJ017; TVSQB: $products_json = file_get_contents(__DIR__ . "\x2f\56\56\x2f\160\x72\x6f\x64\x75\143\164\x73\x2e\152\x73\157\x6e"); goto VVtbl; IJLym: $all_products = array(); goto L_VT1; mJ017: if (!isset($_SESSION["\141\x64\x6d\151\x6e\x5f\154\157\147\147\145\144\137\x69\156"])) { header("\x4c\x6f\x63\x61\x74\x69\157\156\72\x20\154\157\147\x69\156\56\160\150\x70"); die; } goto TVSQB; AEE5F: ?>
</tbody></table></div></main></div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></body></html>